SOCCER_SUPPORTED_LEAGUES = {
    "eng.1": "Premier League",
    "eng.2": "Championship",
    "esp.1": "La Liga",
    "ger.1": "Bundesliga",
    "ita.1": "Serie A",
    "fra.1": "Ligue 1",
    "usa.1": "MLS",
    "usa.nwsl": "NWSL",
    "uefa.champions": "Champions League",
    "uefa.europa": "Europa League",
    "uefa.europa.conf": "Europa Conference League",
    "fifa.world": "World Cup",
    "mex.1": "Liga MX",
    "ned.1": "Eredivisie",
    "por.1": "Primeira Liga",
    "ksa.1": "Saudi Pro League",
    "conmebol.libertadores": "Copa Libertadores",
    "fifa.friendly": "Amistosos Internacionales",
    "fifa.worldq.uefa":"Uefa Repechage", 
    "arg.1":"Liga Argentina", 
    "conmebol.sudamericana": "Copa Sudamericana",
    "bra.1":"Brasileirao", 
    "nor.1": "Eliteserien",
}
